# Generated by Django 3.0.7 on 2020-06-13 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0002_accommodation_activity_flight_room'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='check_in_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='checkout_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
