# Generated by Django 3.0.7 on 2020-06-15 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0003_auto_20200613_0449'),
    ]

    operations = [
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_accepted', models.BooleanField()),
                ('current_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consilium_api.Traveler')),
                ('friend_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friends', to='consilium_api.Traveler')),
            ],
            options={
                'verbose_name': 'friend',
                'verbose_name_plural': 'friends',
            },
        ),
    ]
