# Generated by Django 3.0.7 on 2020-06-16 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0004_friend'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Traveler_Trip',
            new_name='TravelerTrip',
        ),
        migrations.AlterModelOptions(
            name='travelertrip',
            options={'verbose_name': 'traveler trip', 'verbose_name_plural': 'traveler trips'},
        ),
    ]
