# Generated by Django 3.0.7 on 2020-06-16 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0005_auto_20200616_1718'),
    ]

    operations = [
        migrations.AddField(
            model_name='traveler',
            name='trip_for_traveler',
            field=models.ManyToManyField(through='consilium_api.TravelerTrip', to='consilium_api.Trip'),
        ),
        migrations.AddField(
            model_name='trip',
            name='traveler_on_trip',
            field=models.ManyToManyField(through='consilium_api.TravelerTrip', to='consilium_api.Traveler'),
        ),
    ]
