# Generated by Django 3.0.7 on 2020-06-18 05:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0007_traveler_possible_friend'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accommodation',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='flight',
            name='trip',
        ),
        migrations.CreateModel(
            name='TripFlight',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consilium_api.Flight')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consilium_api.Trip')),
            ],
        ),
        migrations.CreateModel(
            name='TripAccommodation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consilium_api.Accommodation')),
                ('trip', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='consilium_api.Trip')),
            ],
        ),
        migrations.AddField(
            model_name='trip',
            name='accommodation',
            field=models.ManyToManyField(through='consilium_api.TripAccommodation', to='consilium_api.Accommodation'),
        ),
        migrations.AddField(
            model_name='trip',
            name='flight',
            field=models.ManyToManyField(through='consilium_api.TripFlight', to='consilium_api.Flight'),
        ),
    ]
