# Generated by Django 3.0.7 on 2020-06-18 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0008_auto_20200618_0534'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tripflight',
            name='flight',
        ),
        migrations.RemoveField(
            model_name='tripflight',
            name='trip',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='flight',
        ),
        migrations.AddField(
            model_name='flight',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='consilium_api.Trip'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='TripAccommodation',
        ),
        migrations.DeleteModel(
            name='TripFlight',
        ),
    ]
