# Generated by Django 3.0.7 on 2020-06-18 16:51

from django.db import migrations, models
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0009_auto_20200618_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='flight',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('destination_airport')),), 'verbose_name': 'flight', 'verbose_name_plural': 'flights'},
        ),
        migrations.AlterField(
            model_name='flight',
            name='arrival_time',
            field=models.CharField(max_length=55),
        ),
    ]
