# Generated by Django 3.0.7 on 2020-06-18 18:50

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0010_auto_20200618_1651'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trip',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('start_date')),), 'verbose_name': 'trip', 'verbose_name_plural': 'trips'},
        ),
        migrations.AddField(
            model_name='accommodation',
            name='trip',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='consilium_api.Trip'),
            preserve_default=False,
        ),
    ]
