# Generated by Django 3.0.7 on 2020-06-18 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0011_auto_20200618_1850'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('trip')), 'check_in_date')},
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='consilium_api.Room'),
        ),
    ]
