# Generated by Django 3.0.7 on 2020-06-19 04:22

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0012_auto_20200618_1907'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('trip')), 'city'), 'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
    ]
