# Generated by Django 3.0.7 on 2020-06-22 04:53

from django.db import migrations
import django.db.models.expressions


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0013_auto_20200619_0422'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accommodation',
            options={'ordering': (django.db.models.expressions.OrderBy(django.db.models.expressions.F('trip')), 'checkin_date')},
        ),
        migrations.RenameField(
            model_name='accommodation',
            old_name='check_in_date',
            new_name='checkin_date',
        ),
    ]
