# Generated by Django 3.0.7 on 2020-06-23 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0015_auto_20200623_1511'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='consilium_api.Room'),
        ),
        migrations.AlterField(
            model_name='room',
            name='room_number',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
