# Generated by Django 3.0.7 on 2020-06-23 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('consilium_api', '0016_auto_20200623_1525'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='room',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='consilium_api.Room'),
        ),
    ]
